version: '3.4'

services:
  avup.fun:
    image: ${DOCKER_REGISTRY-}avupfun
    build:
      context: .
      dockerfile: AVUP.Fun/Dockerfile
    depends_on:
      - clickhouse-server
      - broker
    ports:
      - 127.0.0.1:80:80
    networks:
      - clickhouse
      - kafka

  intake:
    image: ${DOCKER_REGISTRY-}avupfunintake
    build:
      context: .
      dockerfile: AVUP.Fun.Intake/Dockerfile
    depends_on:
      - clickhouse-server
      - broker
    ports:
      - 127.0.0.1:81:80
    networks:
      - clickhouse
      - kafka
  process:
    image: ${DOCKER_REGISTRY-}avupfunprocess
    build:
      context: .
      dockerfile: AVUP.Fun.Process/Dockerfile
    depends_on:
      - clickhouse-server
      - broker
    ports:
      - 127.0.0.1:82:80
    networks:
      - clickhouse
      - kafka

  clickhouse-server:
    image: yandex/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - clickhouse
      - kafka
    volumes:
      - clickhouse:/var/lib/clickhouse

  clickhouse-client:
    image: yandex/clickhouse-client
    networks:
      - clickhouse
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    networks:
      - kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:7.0.1
    hostname: broker
    depends_on:
      - zookeeper
    networks:
      - kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

networks:
  clickhouse:
  kafka:

volumes:
  clickhouse: