name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t "127.0.0.1:42266/avupfun" --label "com.microsoft.created-by=visual-studio" --label "com.microsoft.visual-studio.project-name=AVUP.Fun" -f ./AVUP.Fun/Dockerfile .
